FROM python:3.11

WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy only the necessary files to install dependencies with Poetry
COPY pyproject.toml poetry.lock ./

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --only main --no-interaction --no-ansi

# Copy app files.
COPY examples/combined /app

# Copy scraping sources.
COPY examples/combined/scraper_worker/sources.csv /app
